In [3]:
# tensor operations
import torch





In [8]:
# create tensors
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

# element-wise addition
z = x + y
print(z)

tensor([5, 7, 9])


In [5]:
x + 2

tensor([3, 4, 5])

In [4]:
# element-wise multiplication of two tensors
z = x * y 
print(z)
# element-wise division of two tensors
z = x / y 
print(z)

tensor([ 4, 10, 18])
tensor([0.2500, 0.4000, 0.5000])


In [13]:
z = torch.mul(x, 3)  # [1,2,3] * 3 = [3,6,9]
print(z)

z = torch.mul(x, y)  # [1,2,3] * [4,5,6] = [4,10,18]
print(z)

# z = torch.mul(x, [1,2])  # [1,2,3] * [1,2] = error
# print(z)

tensor([3, 6, 9])
tensor([ 4, 10, 18])


### Dot Product

In [14]:
z = torch.matmul(x, y) # [1,2,3] 
print(z)

tensor(32)


In [15]:
x_tensor = torch.rand(3, 4)
y_tensor = torch.rand(4,3)
z_tensor = torch.matmul(x_tensor, y_tensor)
print(z_tensor)

tensor([[0.8627, 1.1691, 0.8586],
        [1.1404, 0.9494, 1.0062],
        [0.7843, 1.1645, 1.2830]])


### nn.Module

In [17]:
from torch import nn

In [18]:
linear_layer = nn.Linear(in_features=10, out_features=5)
print(linear_layer)

Linear(in_features=10, out_features=5, bias=True)


In [25]:
tensor_l = torch.rand(size=(5,10))
print(tensor_l)

tensor([[0.2086, 0.6150, 0.1395, 0.4470, 0.9715, 0.3505, 0.6383, 0.9162, 0.4367,
         0.2213],
        [0.1426, 0.2580, 0.7302, 0.9146, 0.4341, 0.8564, 0.0193, 0.0448, 0.2698,
         0.5216],
        [0.0776, 0.9536, 0.0922, 0.4856, 0.2090, 0.2386, 0.1345, 0.6514, 0.2010,
         0.0108],
        [0.8446, 0.4304, 0.3484, 0.0318, 0.2254, 0.0987, 0.1848, 0.4165, 0.3419,
         0.9037],
        [0.5689, 0.0396, 0.9721, 0.4081, 0.6629, 0.2503, 0.6992, 0.3227, 0.8606,
         0.8632]])


In [28]:
x = linear_layer(tensor_l)
x

tensor([[ 0.2043, -0.5393, -0.1496, -0.2216,  0.0889],
        [ 0.2827, -0.1430, -0.1188, -0.1786, -0.2571],
        [ 0.0730, -0.5332,  0.0623, -0.2023, -0.2360],
        [ 0.2599, -0.5148,  0.2512,  0.0108,  0.1413],
        [ 0.1726, -0.1691, -0.1729, -0.2580,  0.0770]],
       grad_fn=<AddmmBackward0>)

In [29]:
v = torch.arange(1, 6)
print(v)

tensor([1, 2, 3, 4, 5])


In [34]:
print("min: ",v.min())
print("max: ",v.max())
print("mean: ",v.double().mean())
print("std: ",v.double().std())

min:  tensor(1)
max:  tensor(5)
mean:  tensor(3., dtype=torch.float64)
std:  tensor(1.5811, dtype=torch.float64)


In [39]:
max_index = v.argmax()
print("max_index",max_index)

min_index = v.argmin()
print("max_index",min_index)

max_index tensor(4)
max_index tensor(0)


### Floating cast

In [51]:
# 1
float_vec = torch.arange(0, 10, 1.)
print(float_vec)
print(float_vec.dtype)
print(type(float_vec),"\n")

# 2
float_vec = float_vec.to(torch.float32)
print(float_vec)
print(float_vec.dtype)
print(type(float_vec),"\n")

# 3
print(float_vec.double())
print(float_vec.dtype)
print(type(float_vec.double()),"\n")


# 4
      ## This will give an error

# float_vec = float_vec.dtype(torch.float64)
# print(float_vec)
# print(float_vec.dtype)
# print(type(float_vec),"\n")

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
torch.float32
<class 'torch.Tensor'> 

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
torch.float32
<class 'torch.Tensor'> 

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)
torch.float32
<class 'torch.Tensor'> 



TypeError: 'torch.dtype' object is not callable