In [3]:
# tensor operations
import torch





In [8]:
# create tensors
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

# element-wise addition
z = x + y
print(z)

tensor([5, 7, 9])


In [5]:
x + 2

tensor([3, 4, 5])

In [4]:
# element-wise multiplication of two tensors
z = x * y 
print(z)
# element-wise division of two tensors
z = x / y 
print(z)

tensor([ 4, 10, 18])
tensor([0.2500, 0.4000, 0.5000])


In [13]:
z = torch.mul(x, 3)  # [1,2,3] * 3 = [3,6,9]
print(z)

z = torch.mul(x, y)  # [1,2,3] * [4,5,6] = [4,10,18]
print(z)

# z = torch.mul(x, [1,2])  # [1,2,3] * [1,2] = error
# print(z)

tensor([3, 6, 9])
tensor([ 4, 10, 18])


In [14]:
z = torch.matmul(x, y) # [1,2,3] 
print(z)

tensor(32)
