In [1]:
import torch
import torch.nn as nn


## Tensor Transpose

In [7]:
x = torch.rand(5, 3)
print(x,"\n")

# 1:
transposed_tensor = x.transpose(0, 1)
print(transposed_tensor)

# 2:
transposed_tensor = x.t()
print("\n",transposed_tensor)

tensor([[0.4235, 0.0663, 0.8680],
        [0.5117, 0.1961, 0.3378],
        [0.9194, 0.3425, 0.4114],
        [0.6146, 0.3478, 0.4494],
        [0.5959, 0.4499, 0.2795]]) 

tensor([[0.4235, 0.5117, 0.9194, 0.6146, 0.5959],
        [0.0663, 0.1961, 0.3425, 0.3478, 0.4499],
        [0.8680, 0.3378, 0.4114, 0.4494, 0.2795]])

 tensor([[0.4235, 0.5117, 0.9194, 0.6146, 0.5959],
        [0.0663, 0.1961, 0.3425, 0.3478, 0.4499],
        [0.8680, 0.3378, 0.4114, 0.4494, 0.2795]])
