In [2]:
import torch


In [3]:
random_tensor = torch.rand(3, 4)
print(random_tensor)

tensor([[0.2323, 0.5032, 0.9048, 0.9535],
        [0.3815, 0.3841, 0.0751, 0.5889],
        [0.9577, 0.3670, 0.1497, 0.0023]])


In [20]:
vect = torch.tensor([1, 2, 3, 4, 5])
print(vect.shape)
print(vect.dtype)
# print(vect.device)
# print(vect.requires_grad)
# print(vect.is_leaf)
# print(vect.data_ptr())
# print(vect.storage())
print(vect.ndim)
print(vect.size())

torch.Size([5])
torch.int64
1
torch.Size([5])


In [23]:
torch.ones(3, 4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
torch.zeros(3, 4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
#arange the code in the order of execution
torch.arange(1, 10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
r_tensor = torch.tensor([1, 2, 3],
                        dtype=torch.float32,
                        requires_grad=True,
                        device='cuda')
r_tensor

tensor([1., 2., 3.], device='cuda:0', requires_grad=True)