### (transpose, stacking, squeezing, unsqueezing, permute)

In [1]:
import torch
import torch.nn as nn


## Tensor Transpose

In [2]:
x = torch.rand(5, 3)
print(x,"\n")

# 1:
transposed_tensor = x.transpose(0, 1)
print(transposed_tensor)

# 2:
transposed_tensor = x.t()
print("\n",transposed_tensor)

tensor([[0.8000, 0.5987, 0.2172],
        [0.9040, 0.6076, 0.8586],
        [0.9476, 0.6811, 0.6815],
        [0.6464, 0.1212, 0.8527],
        [0.2308, 0.6495, 0.7168]]) 

tensor([[0.8000, 0.9040, 0.9476, 0.6464, 0.2308],
        [0.5987, 0.6076, 0.6811, 0.1212, 0.6495],
        [0.2172, 0.8586, 0.6815, 0.8527, 0.7168]])

 tensor([[0.8000, 0.9040, 0.9476, 0.6464, 0.2308],
        [0.5987, 0.6076, 0.6811, 0.1212, 0.6495],
        [0.2172, 0.8586, 0.6815, 0.8527, 0.7168]])


In [15]:
tens = torch.arange(0, 10)
tens.reshape(1,-1)


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

# Stacking

In [20]:
x_stacked = torch.stack([x, x], dim=0)
print(x_stacked,"\n")

x_stacked = torch.stack([x, x], dim=1)
print(x_stacked,"\n")


tensor([[[0.8000, 0.5987, 0.2172],
         [0.9040, 0.6076, 0.8586],
         [0.9476, 0.6811, 0.6815],
         [0.6464, 0.1212, 0.8527],
         [0.2308, 0.6495, 0.7168]],

        [[0.8000, 0.5987, 0.2172],
         [0.9040, 0.6076, 0.8586],
         [0.9476, 0.6811, 0.6815],
         [0.6464, 0.1212, 0.8527],
         [0.2308, 0.6495, 0.7168]]]) 

tensor([[[0.8000, 0.5987, 0.2172],
         [0.8000, 0.5987, 0.2172]],

        [[0.9040, 0.6076, 0.8586],
         [0.9040, 0.6076, 0.8586]],

        [[0.9476, 0.6811, 0.6815],
         [0.9476, 0.6811, 0.6815]],

        [[0.6464, 0.1212, 0.8527],
         [0.6464, 0.1212, 0.8527]],

        [[0.2308, 0.6495, 0.7168],
         [0.2308, 0.6495, 0.7168]]]) 



# Squeeze and Unsqueeze

In [21]:
vector1 = torch.arange(0, 20)
vector1.reshape(4, 5)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [22]:
squeezed = torch.squeeze(vector1)
print(squeezed)
print(squeezed.shape)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])
torch.Size([20])


In [27]:
unsqueezed = squeezed.unsqueeze(dim=0)
print(unsqueezed.shape)

unsqueezed = squeezed.unsqueeze(dim=1)
print(unsqueezed.shape)

unsqueezed = vector1.unsqueeze(dim=0)
print(unsqueezed.shape)

torch.Size([1, 20])
torch.Size([20, 1])
torch.Size([1, 20])


# Permute the dimensions of a tensor

In [31]:
vec = torch.rand(224,224,3)
print(vec.shape)
vec_permuted = vec.permute(2,0,1)
print(vec_permuted.shape)

torch.Size([224, 224, 3])
torch.Size([3, 224, 224])
